services:
  # MySQL Database Service
  mysql:
    image: mysql:8.4.5
    container_name: erp-mysql
#    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: erp_db
      MYSQL_USER: erp_user
      MYSQL_PASSWORD: erp_password
      TZ: Asia/Taipei
    ports:
      - "30306:3306"
    volumes:
      - ./MySQL/data:/var/lib/mysql
    networks:
      - erp-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.2
    container_name: erp-phpmyadmin
#    restart: always
    environment:
      PMA_HOST: mysql           # MySQL 服務名稱（Docker Compose 服務名）
      PMA_PORT: 3306            # MySQL 連接埠
      PMA_USER: root            # 預設登入使用者
      PMA_PASSWORD: root        # 預設登入密碼
      PMA_ARBITRARY: 1          # 允許使用者手動輸入其他主機
    ports:
      - "30310:80"
    depends_on:
      - mysql
    networks:
      - erp-network

  # Redis Service
  redis:
    image: redis:7.4.5
    container_name: erp-redis
    restart: unless-stopped
    ports:
      - "30312:6379"
    volumes:
      - ./redis/data:/data              # 持久化 RDB 快照與 AOF 日誌存放
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf  # 自訂 Redis 設定檔（非必須）
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - erp-network

  # Core Application Service
  core:
    build:
      context: ..
      dockerfile: docker/core/Dockerfile
    container_name: erp-core
    # restart: unless-stopped
    ports:
      - "30308:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/erp_db
      - SPRING_DATASOURCE_USERNAME=erp_user
      - SPRING_DATASOURCE_PASSWORD=erp_password
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    depends_on:
      - mysql
      - redis
    networks:
      - erp-network

networks:
  erp-network:
    driver: bridge
