spring:
  application:
    name: core
  
  # Database Configuration (MySQL) - Docker 環境
  datasource:
    url: jdbc:mysql://mysql:3306/erp_db?useSSL=false&serverTimezone=Asia/Taipei&allowPublicKeyRetrieval=true
    username: erp_user
    password: erp_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false  # 在生產環境中關閉 SQL 日誌
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
  
  # Redis Configuration - Docker 環境
  data:
    redis:
      host: redis
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

# Server Configuration
server:
  port: 8080

# Logging Configuration - Docker 環境優化
logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    org.springframework: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
